// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjLaQSVtIk8w3nWve7PF5PwbtxGzjIogI',
    appId: '1:283184840115:web:47874fb6e118979b461fc6',
    messagingSenderId: '283184840115',
    projectId: 'care-2a20d',
    authDomain: 'care-2a20d.firebaseapp.com',
    storageBucket: 'care-2a20d.firebasestorage.app',
    measurementId: 'G-44NX3FCVZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_lx2VlsU4cCb0O6S70BYvdLAvDegcrZ8',
    appId: '1:283184840115:android:3ba51ec94fc905bc461fc6',
    messagingSenderId: '283184840115',
    projectId: 'care-2a20d',
    storageBucket: 'care-2a20d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR6c28pS01jO_DQkx9DVA1tk_fuQeGV-w',
    appId: '1:283184840115:ios:3b4f9039324e90f7461fc6',
    messagingSenderId: '283184840115',
    projectId: 'care-2a20d',
    storageBucket: 'care-2a20d.firebasestorage.app',
    androidClientId: '283184840115-86vkleok9as8m7qipsto4k6u42obov1g.apps.googleusercontent.com',
    iosClientId: '283184840115-hrrokdp8qbig9p9ql816tohgk8l3pf11.apps.googleusercontent.com',
    iosBundleId: 'com.kina.goldenHandCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR6c28pS01jO_DQkx9DVA1tk_fuQeGV-w',
    appId: '1:283184840115:ios:3b4f9039324e90f7461fc6',
    messagingSenderId: '283184840115',
    projectId: 'care-2a20d',
    storageBucket: 'care-2a20d.firebasestorage.app',
    androidClientId: '283184840115-86vkleok9as8m7qipsto4k6u42obov1g.apps.googleusercontent.com',
    iosClientId: '283184840115-hrrokdp8qbig9p9ql816tohgk8l3pf11.apps.googleusercontent.com',
    iosBundleId: 'com.kina.goldenHandCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjLaQSVtIk8w3nWve7PF5PwbtxGzjIogI',
    appId: '1:283184840115:web:78738d61fff3ed59461fc6',
    messagingSenderId: '283184840115',
    projectId: 'care-2a20d',
    authDomain: 'care-2a20d.firebaseapp.com',
    storageBucket: 'care-2a20d.firebasestorage.app',
    measurementId: 'G-LMH5C9M40R',
  );
}
